apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
spec:
  containers:
    - name: web
      image: docker.io/library/alpine:latest
      command:
        - sleep
        - "5000"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP